### ISSUE TITLE
Provide a callback that refreshes profile data in Profile Header after updating profile on Profile Settings

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs#19]

**Comment by esokullu** [comment]
If you write it wrapped up with ```unescape(str)``` method, it should display properly.

**Comment by ozanilbey** [comment]
Done!

**Comment by esokullu** [comment]
Great, is it clear in the documentation as well so that developers can reach the functionality in a snap.

**Comment by ozanilbey** [comment]
Mentioned "callback" is not for users. It is for the related tags to communicate between them. Everything is automatically works now.
