### ISSUE TITLE
no delete buttons in forum

### ISSUE THREAD

**Issue by esokullu** [pho-incubator/graphjs#32]
founder and content owner should be able to delete.
owner should be able to edit as well.

may apply elsewhere as well.

**Comment by ozanilbey** [comment]
None of these are not possible in the current situation because there is no reply id in getThread(id).

Sample request: http://phonetworks.com:1338/getThread?id=595eab35744c5cb1f2985cec7c82cb1b&public_id=79982844-6a27-4b3b-b77f-419a79be0e10

**Comment by esokullu** [comment]
Good reporting, thanks for sharing the request as well.
Fixed in the latest graphjs-server commit https://github.com/phonetworks/graphjs-server/commit/209974dec919bd3c650f5597e636bb862accda1d
