### ISSUE TITLE
Unreadable error messsages in Forum

### ISSUE THREAD

**Issue by esokullu** [pho-incubator/graphjs#35]
Title is too short error as follows:
![image](https://user-images.githubusercontent.com/19166/38429568-7155ceca-39c7-11e8-9e63-94278c476eb7.png)

**Comment by esokullu** [comment]
?

**Comment by ozanilbey** [comment]
Didn't have chance to look for this. Will handle in 2-3 days.

**Comment by ozanilbey** [comment]
Fixed this. If this occurs again, please provide a new screenshot. It's unlikely but... just in case.
