### ISSUE TITLE
Comments in "powered by graphjs" may be at the top

### ISSUE THREAD

**Issue by esokullu** [pho-incubator/graphjs#37]
Otherwise it can go too much in the bottom. And it doesn't seem to break the layout if it's at the top. 

There may be other such examples too, we should prefer top unless it breaks the layout.

**Comment by esokullu** [comment]
?

**Comment by ozanilbey** [comment]
Didn't have chance to look for this. Will handle in 2-3 days.

**Comment by ozanilbey** [comment]
Do you need this only for Comments component?

**Comment by esokullu** [comment]
I believe so. Can you think of anywhere else?

**Comment by ozanilbey** [comment]
Okay, I'll fix that. If I notice something similar, I'll fix that, too.

**Comment by ozanilbey** [comment]
Done!
