### ISSUE TITLE
maxwidth maxheight parameters

### ISSUE THREAD

**Issue by esokullu** [pho-incubator/graphjs#38]
Parameters should use dash:
example: max-width, max-height

**Comment by ozanilbey** [comment]
Properties with dash are transformed to camel-case automatically. Do you really want this?

**Comment by esokullu** [comment]
Transformed to camel-case automatically? At what step?

I do want it, this is not readable and it's not a good practice.

**Comment by ozanilbey** [comment]
For example, Riot let you reach maxwidth value as opts.maxwidth in your code. If the attribute name is max-width, you cannot reach it as opts.max-width. It is only possible to reach as opts.maxWidth, and this can be confusing. Not for me, of course :)

Changed it anyway.
