### ISSUE TITLE
Responsive Design List

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs#43]
- [x] Structure
- [x] Elements
- [x] Model: Box
- [x] Model: Card
- [x] Model: Credit
- [x] Model: Loading
- [x] Model: Promo
- [x] Model: Wallet
- [x] Component: Alert
- [x] Component: Auth Register
- [x] Component: Auth Login
- [x] Component: Auth Reset
- [x] Component: Comments
- [x] Component: Forum List
- [x] Component: Forum Thread
- [x] Component: Forum Compose
- [x] Component: Group
- [x] Component: Group Card
- [x] Component: Group Header
- [ ] Component: Group Activity
- [x] Component: Group Members
- [x] Component: Group Settings
- [x] Component: Group Creator
- [x] Component: List (Formerly "Wallet")
- [x] Component: Messages
- [x] Component: Messages Composer
- [x] Component: Profile
- [x] Component: Profile Card
- [x] Component: Profile Header
- [ ] Component: Profile Activity
- [x] Component: Profile Followers
- [x] Component: Profile Following
- [x] Component: Profile Groups
- [x] Component: Profile Settings
- [x] Component: Star List
- [x] Component: Star Button
- [x] Component: State
- [x] Pseudo Component: Overlay

**Comment by ozanilbey** [comment]
State and Star Button will not be responsive because they are already small.

**Comment by ozanilbey** [comment]
Profile Activity and Group Activity are not ready yet. Will revisit them later.

**Comment by ozanilbey** [comment]
Forum Thread is completed more than 90%; however, it's not possible to move on as getThreads and getThread(id) calls are not working properly.

**Comment by ozanilbey** [comment]
Profile Header and Group Header need to have a responsive menu. There are practically two options for such components: 

1. Turn the text menu into an icon menu on mobile screens.
2. Hide/show menu under a hambuger menu or similar.

**Comment by ozanilbey** [comment]
Loading state of each component should be responsive. It's not a hard one, will do it tomorrow. It will take 3-5 minutes per component.

**Comment by esokullu** [comment]
Re: Profile Header, Group Header
icon menu sounds better.

The rest of my comments can be found as 👍-- means "no action required by me"

**Comment by esokullu** [comment]
> Profile Activity and Group Activity are not ready yet. Will revisit them later.

I'm getting there. Really close.

**Comment by ozanilbey** [comment]
Will create an icon menu, then.

**Comment by esokullu** [comment]
> Forum Thread is completed more than 90%; however, it's not possible to move on as getThreads and getThread(id) calls are not working properly.

restarted graphjs server and it's working fine now.

**Comment by ozanilbey** [comment]
Closing this one
