### ISSUE TITLE
Feed

### ISSUE THREAD

**Issue by esokullu** [pho-incubator/graphjs#44]
1. Log in with the credentials I've provided.
2. It's the GraphJS app.
3. Click Explorer
4. timeline:3c5ce542f02480389222880c1b5703eb is the common feed of the graph. All graph activities go there.
5. When a user signs up, they get a new feed called wall:{user_id} for example "wall:470737707bd9d5fa20a5feaf64468d9c"
6. For more information on the feed format, c/o https://www.w3.org/TR/activitystreams-core/ (don't! too long)
7. Basically, there are four fields with each feed: subject (who did it) object(on what) verb (the action) text (status update in text format, this is the one you're interested)
8. For example, when a user joins, the actor would be themselves, the verb would be "_construct" (normally it's the edge label, but here there's no edge, so it starts with underscore) the object would be null (but null doesn't work with getstream, so in this case, it's a replica of subject. so just ignore it if the verb is "_construct") You may check out activity ID b3a602d2-460a-11e8-81a5-0a081e7097fe to see sample of new user join.
9. Otherwise it's verb: edge label, subject: edge tail id, object: edge head id, text: the update in human readable format
10. in general, wall means a user's feed. timeline means an aggregated feed that follows other user's walls.

**Comment by ozanilbey** [comment]
Closing...
