### ISSUE TITLE
Final Sprint Before v1

### ISSUE THREAD

**Issue by esokullu** [pho-incubator/graphjs#49]
- [x] State, should come with "..." at first. Kinda like Profile:Card
- [x] State does not change when you log in.
- [x] Messages, does not change color when it's read. One has to reload to see the color changres.
- [ ] Activity design with date (e.g. xx days ago) and icons (or just avatars)
- [x] Group:card ... diye takili kaliyor, degismiyor. When logged in. Can't reproduce the bug when it's in List mode.
- [x] Star: List tasarimla ilgili vverdigim feedback; numaranin bir karede gosterilmesi.
- [x] Forum - we need CSS "overflow: auto" so that the vertical scroll bar is shown when there's more content than the rectangle surrounding it.
- [x] Forum bug: https://screencast.com/t/vGJgpU0p
- [x] I assume we've fixed, or will fix, the reset password bug.
- [x] Overlay items should scroll if the component height is bigger than the viewport height
- [x] Solve the problem related to scroll behaviour that makes the scroll bar invisible
- [x] Make List access optional: public/private
- [x] Make Messages: Composer a real component
- [ ] Rename Messages: Composer's component name to message-composer

**Comment by ozanilbey** [comment]
Couldn't understand what the bug is on Forum. Is it a scroll problem? Can you explain?

**Comment by esokullu** [comment]
Sadece scrollbar gorunmuyor, eger icerik uzunsa. Orayi overflow: auto yapmaliyiz, scrollbar gozukmeli.

Ikincide de alan daha fazla yer kapliyor, ekrani geciyor (popup'in icinde) ve scroll down edemiyosun bile

**Comment by ozanilbey** [comment]
![screen shot 2018-04-29 at 4 24 11 pm](https://user-images.githubusercontent.com/3929181/39407116-e02d9d6e-4bc9-11e8-9c32-01af21718555.png)

Bende calisiyor.

**Comment by ozanilbey** [comment]
![screen shot 2018-04-29 at 4 27 53 pm](https://user-images.githubusercontent.com/3929181/39407144-50061cc4-4bca-11e8-9935-fffa26f8d94a.png)

overflow-y: scroll var, yani dikeyde scroll ediliyor.

**Comment by esokullu** [comment]
Bu ilk satira mi cevap, ikinci satira mi?
Ilkiyse scrollbar bende sadece mouse'la indirince gorunuyor.
![image](https://user-images.githubusercontent.com/19166/39407161-cb494874-4b76-11e8-855b-c0b2c31a1c1b.png)

Ikinci satir ayri bi problem; bende pencere 600px height'dayken o problem var.

**Comment by ozanilbey** [comment]
![screen shot 2018-04-29 at 4 47 39 pm](https://user-images.githubusercontent.com/3929181/39407335-1f4659d4-4bcd-11e8-9434-31f2033acc25.png)

Sanirim bu durumu kendi scroll barimizi yaratarak onleyebiliyormusuz: http://jsfiddle.net/Eh7xT/1493/
Ama bu bence dogru bir secim degil.

**Comment by esokullu** [comment]
Evet simdi calisti.

**Comment by ozanilbey** [comment]
Closing this one. Will continue with #41
